#!/usr/bin/env python3
"""Run the frozen V42 validation locally and export aggregates only.

This is validation infrastructure, not a biological analysis. Individual-level
inputs and the harness's paired score table remain in an ephemeral private
directory. Only a fixed aggregate allowlist is exported. Runtime audit hooks
deny network sockets and subprocesses while the frozen harness is executing.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import importlib.util
import json
import os
import platform
import re
import shutil
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
HARNESS = ROOT / "scripts/v42_gafson_validation_harness.py"
DEFAULT_MANIFEST = ROOT / "analysis/v45_author_run_packet_checksums/write/author_run_packet_sha256_manifest.tsv"
MIN_CELL_COUNT = 5

PRIVATE_HARNESS_FILES = {"paired_module_deltas.tsv"}
AGGREGATE_SOURCE_FILES = {
    "validation_summary.json",
    "gene_mapping_coverage.tsv",
    "locked_rule_metrics.tsv",
    "confounder_adjustment_metrics.tsv",
    "joint_confounder_metrics.tsv",
    "batch_diagnostic_metrics.tsv",
}
EXPORT_FILES = AGGREGATE_SOURCE_FILES | {
    "sample_attrition.tsv",
    "RUN_METADATA.txt",
    "validation_result_report.md",
    "EXPORT_ATTESTATION.json",
}
IDENTIFIER_COLUMNS = re.compile(
    r"^(patient|patient_id|sample|sample_id|subject|subject_id|participant|participant_id|gsm|geo_accession)$",
    re.IGNORECASE,
)
IDENTIFIER_VALUES = re.compile(r"\b(?:SYN_)?(?:PATIENT|SUBJECT|SAMPLE|PARTICIPANT|GSM)[_-]?[A-Z0-9]+\b", re.IGNORECASE)
DENIED_AUDIT_EVENTS = {"os.system", "subprocess.Popen", "socket.__new__", "socket.connect", "socket.getaddrinfo"}


def resolve(path: Path) -> Path:
    return path if path.is_absolute() else ROOT / path


def relative(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return "<external-local-path>"


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def read_manifest(path: Path) -> dict[str, str]:
    if not path.exists():
        raise ValueError(f"packet checksum manifest missing: {path}")
    with path.open(newline="") as handle:
        rows = csv.DictReader(handle, delimiter="\t")
        return {str(row.get("path", "")): str(row.get("sha256", "")) for row in rows}


def verify_pinned_files(manifest_path: Path) -> dict[str, str]:
    expected = read_manifest(manifest_path)
    required = [
        "scripts/v42_gafson_validation_harness.py",
        "scripts/v57_code_to_data_validation.py",
    ]
    observed: dict[str, str] = {}
    for relpath in required:
        if relpath not in expected:
            raise ValueError(f"packet manifest does not pin {relpath}")
        path = ROOT / relpath
        observed[relpath] = sha256(path)
        if observed[relpath] != expected[relpath]:
            raise ValueError(f"packet hash mismatch for {relpath}")
    return observed


def load_harness():
    spec = importlib.util.spec_from_file_location("v42_frozen_harness", HARNESS)
    if spec is None or spec.loader is None:
        raise RuntimeError("unable to load frozen V42 harness")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def deny_egress_and_subprocess(event: str, _args: tuple[object, ...]) -> None:
    if event in DENIED_AUDIT_EVENTS:
        raise PermissionError(f"code-to-data execution denied audit event: {event}")


def aggregate_attrition(source: Path, target: Path) -> None:
    table = pd.read_csv(source, sep="\t").fillna("")
    required = {"included", "reason"}
    if not required.issubset(table.columns):
        raise ValueError(f"attrition table missing columns: {sorted(required - set(table.columns))}")
    grouped = (
        table.assign(included=table["included"].astype(str).str.lower().isin({"true", "yes", "1"}))
        .groupby(["included", "reason"], dropna=False)
        .size()
        .reset_index(name="count_exact")
    )
    grouped["count"] = grouped["count_exact"].map(lambda value: str(int(value)) if int(value) >= MIN_CELL_COUNT else f"<{MIN_CELL_COUNT}")
    grouped.drop(columns=["count_exact"]).to_csv(target, sep="\t", index=False)


def auto_report(summary: dict[str, object], synthetic: bool) -> str:
    return (
        "# Aggregate Code-to-Data Validation Output\n\n"
        f"synthetic: {str(synthetic).lower()}\n\n"
        "evidence_status: AUTHOR_RUN_AGGREGATE_UNVERIFIED\n\n"
        "This file was generated by the pinned aggregate-only runner. It is not "
        "a project-grounded finding and must pass the V45/V46 receipt gates before "
        "interpretation under the precommitted V42 outcome grid.\n\n"
        f"- Frozen harness verdict field: `{summary.get('final_verdict', 'UNAVAILABLE')}`\n"
        f"- Labeled paired subjects: `{summary.get('n', 'UNAVAILABLE')}`\n"
        f"- Batch guard flag: `{summary.get('batch_guard_flag', 'UNAVAILABLE')}`\n\n"
        "No participant-level score, expression, sample identifier, or patient "
        "identifier is exported by this package.\n"
    )


def write_metadata(target: Path, hashes: dict[str, str], expression: Path, metadata: Path, synthetic: bool) -> None:
    lines = [
        f"synthetic: {str(synthetic).lower()}",
        "purpose: privacy-preserving code-to-data execution; no biological claim",
        "evidence_status: AUTHOR_RUN_AGGREGATE_UNVERIFIED",
        "command: python scripts/v57_code_to_data_validation.py run --expression <LOCAL_EXPRESSION> --metadata <LOCAL_METADATA> --outdir <AGGREGATE_EXPORT> --expression-type <FROZEN_CHOICE>",
        f"software: python={platform.python_version()}; numpy={np.__version__}; pandas={pd.__version__}",
        f"runner_sha256: {hashes['scripts/v57_code_to_data_validation.py']}",
        f"harness_sha256: {hashes['scripts/v42_gafson_validation_harness.py']}",
        f"expression_sha256: {sha256(expression)}",
        f"metadata_sha256: {sha256(metadata)}",
        "network_and_subprocess_audit_hook: enabled",
        "private_staging_retained: false",
        f"minimum_export_cell_count: {MIN_CELL_COUNT}",
        f"run_utc: {datetime.now(timezone.utc).replace(microsecond=0).isoformat()}",
    ]
    target.write_text("\n".join(lines) + "\n")


def scan_export(outdir: Path, require_attestation: bool = True) -> list[str]:
    problems: list[str] = []
    observed = {path.name for path in outdir.iterdir() if path.is_file()}
    required = EXPORT_FILES if require_attestation else EXPORT_FILES - {"EXPORT_ATTESTATION.json"}
    for missing in sorted(required - observed):
        problems.append(f"missing_required_file:{missing}")
    for extra in sorted(observed - EXPORT_FILES):
        problems.append(f"unexpected_export_file:{extra}")
    for private in sorted(PRIVATE_HARNESS_FILES & observed):
        problems.append(f"private_harness_file_exported:{private}")
    for path in sorted(p for p in outdir.iterdir() if p.is_file() and p.suffix.lower() in {".tsv", ".csv"}):
        delimiter = "\t" if path.suffix.lower() == ".tsv" else ","
        with path.open(newline="", errors="ignore") as handle:
            reader = csv.reader(handle, delimiter=delimiter)
            header = next(reader, [])
            bad_columns = [column for column in header if IDENTIFIER_COLUMNS.match(column.strip())]
            if bad_columns:
                problems.append(f"identifier_columns:{path.name}:{','.join(bad_columns)}")
        if IDENTIFIER_VALUES.search(path.read_text(errors="ignore")):
            problems.append(f"identifier_like_values:{path.name}")
    return problems


def write_attestation(outdir: Path, pinned_hashes: dict[str, str], synthetic: bool) -> dict[str, object]:
    problems = scan_export(outdir, require_attestation=False)
    file_hashes = {
        path.name: sha256(path)
        for path in sorted(outdir.iterdir())
        if path.is_file() and path.name != "EXPORT_ATTESTATION.json"
    }
    attestation: dict[str, object] = {
        "synthetic": synthetic,
        "purpose": "aggregate-only code-to-data export attestation; no biological claim",
        "evidence_status": "AUTHOR_RUN_AGGREGATE_UNVERIFIED",
        "project_grounding_status": "unavailable_without_rerunnable_data",
        "network_and_subprocess_audit_hook": "enabled",
        "private_staging_retained": False,
        "minimum_export_cell_count": MIN_CELL_COUNT,
        "pinned_code_sha256": pinned_hashes,
        "export_file_sha256": file_hashes,
        "scan_problems": problems,
        "overall_status": "PASS" if not problems else "FAIL",
    }
    (outdir / "EXPORT_ATTESTATION.json").write_text(json.dumps(attestation, indent=2, sort_keys=True) + "\n")
    return attestation


def verify_export(outdir: Path, fail_on_error: bool) -> tuple[int, dict[str, object]]:
    problems = scan_export(outdir)
    attestation_path = outdir / "EXPORT_ATTESTATION.json"
    try:
        attestation = json.loads(attestation_path.read_text())
    except Exception as exc:
        attestation = {}
        problems.append(f"attestation_unreadable:{exc}")
    expected_hashes = attestation.get("export_file_sha256", {}) if isinstance(attestation, dict) else {}
    if not isinstance(expected_hashes, dict):
        problems.append("attestation_hash_map_invalid")
        expected_hashes = {}
    for name, expected in expected_hashes.items():
        path = outdir / str(name)
        if not path.exists():
            problems.append(f"attested_file_missing:{name}")
        elif sha256(path) != expected:
            problems.append(f"attested_hash_mismatch:{name}")
    for name in sorted((EXPORT_FILES - {"EXPORT_ATTESTATION.json"}) - set(expected_hashes)):
        problems.append(f"file_not_attested:{name}")
    summary = {
        "purpose": "aggregate-only code-to-data export verification; no biological claim",
        "outdir": relative(outdir),
        "n_problems": len(set(problems)),
        "problems": sorted(set(problems)),
        "overall_status": "PASS" if not problems else "FAIL",
    }
    print(json.dumps(summary, indent=2, sort_keys=True))
    return (1 if fail_on_error and problems else 0), summary


def run_local(
    expression: Path,
    metadata: Path,
    outdir: Path,
    expression_type: str,
    manifest: Path,
    synthetic: bool,
) -> dict[str, object]:
    if outdir.exists() and any(outdir.iterdir()):
        raise ValueError(f"refusing non-empty export directory: {outdir}")
    outdir.mkdir(parents=True, exist_ok=True)
    pinned_hashes = verify_pinned_files(manifest)
    harness = load_harness()
    sys.addaudithook(deny_egress_and_subprocess)
    with tempfile.TemporaryDirectory(prefix="v57_private_validation_") as private_dir:
        private = Path(private_dir)
        result = harness.run_validation(expression, metadata, private, expression_type)
        for name in sorted(AGGREGATE_SOURCE_FILES):
            shutil.copyfile(private / name, outdir / name)
        aggregate_attrition(private / "sample_attrition.tsv", outdir / "sample_attrition.tsv")
        write_metadata(outdir / "RUN_METADATA.txt", pinned_hashes, expression, metadata, synthetic)
        (outdir / "validation_result_report.md").write_text(auto_report(result.summary, synthetic))
    attestation = write_attestation(outdir, pinned_hashes, synthetic)
    rc, verify_summary = verify_export(outdir, True)
    if rc:
        raise ValueError(f"aggregate export failed verification: {verify_summary['problems']}")
    return attestation


def synthetic_check(outdir: Path, manifest: Path) -> int:
    if outdir.exists():
        shutil.rmtree(outdir)
    good = outdir / "synthetic_valid_export"
    expression = ROOT / "analysis/v42_harness_validation/planted_inputs/synthetic_expression.tsv"
    metadata = ROOT / "analysis/v42_harness_validation/planted_inputs/synthetic_metadata.tsv"
    attestation = run_local(expression, metadata, good, "normalized_log", manifest, True)

    tampered = outdir / "synthetic_tampered_export"
    shutil.copytree(good, tampered)
    with (tampered / "locked_rule_metrics.tsv").open("a") as handle:
        handle.write("# synthetic tamper\n")
    _, tampered_summary = verify_export(tampered, False)

    leaked = outdir / "synthetic_leaked_export"
    shutil.copytree(good, leaked)
    (leaked / "paired_module_deltas.tsv").write_text("patient_id\tvalue\nSYN_PATIENT_001\t1\n")
    _, leaked_summary = verify_export(leaked, False)

    summary = {
        "synthetic": True,
        "purpose": "code-to-data privacy/tamper regression; no biological claim",
        "valid_export_status": attestation["overall_status"],
        "tampered_export_status": tampered_summary["overall_status"],
        "tamper_detected": "attested_hash_mismatch:locked_rule_metrics.tsv" in tampered_summary["problems"],
        "leaked_export_status": leaked_summary["overall_status"],
        "leak_detected": any("paired_module_deltas.tsv" in problem for problem in leaked_summary["problems"]),
        "private_score_table_exported": (good / "paired_module_deltas.tsv").exists(),
        "overall_status": "PASS",
    }
    if not (
        summary["valid_export_status"] == "PASS"
        and summary["tampered_export_status"] == "FAIL"
        and summary["tamper_detected"]
        and summary["leaked_export_status"] == "FAIL"
        and summary["leak_detected"]
        and not summary["private_score_table_exported"]
    ):
        summary["overall_status"] = "FAIL"
    (outdir / "synthetic_check_summary.json").write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
    print(json.dumps(summary, indent=2, sort_keys=True))
    return 0 if summary["overall_status"] == "PASS" else 2


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    run = sub.add_parser("run")
    run.add_argument("--expression", type=Path, required=True)
    run.add_argument("--metadata", type=Path, required=True)
    run.add_argument("--outdir", type=Path, required=True)
    run.add_argument("--expression-type", choices=["auto", "raw_counts", "normalized_log"], default="auto")
    run.add_argument("--packet-manifest", type=Path, default=DEFAULT_MANIFEST)
    run.add_argument("--synthetic", action="store_true", help="mark a method-only synthetic execution")
    verify = sub.add_parser("verify-export")
    verify.add_argument("--outdir", type=Path, required=True)
    verify.add_argument("--fail-on-error", action="store_true")
    syn = sub.add_parser("synthetic-check")
    syn.add_argument("--outdir", type=Path, default=ROOT / "analysis/v57_code_to_data_validation")
    syn.add_argument("--packet-manifest", type=Path, default=DEFAULT_MANIFEST)
    return parser


def main() -> int:
    args = build_parser().parse_args()
    if args.command == "run":
        attestation = run_local(
            resolve(args.expression),
            resolve(args.metadata),
            resolve(args.outdir),
            args.expression_type,
            resolve(args.packet_manifest),
            args.synthetic,
        )
        print(json.dumps(attestation, indent=2, sort_keys=True))
        return 0
    if args.command == "verify-export":
        return verify_export(resolve(args.outdir), args.fail_on_error)[0]
    return synthetic_check(resolve(args.outdir), resolve(args.packet_manifest))


if __name__ == "__main__":
    raise SystemExit(main())
