#!/usr/bin/env python3
"""Characterize a donor-replicated multi-outcome perturbation gate.

All observations generated by this script are seeded synthetic method-test
data. They are not biological evidence and must not be interpreted as MS
findings.
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

import numpy as np
from scipy import stats


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTDIR = ROOT / "analysis/v57_multicriterion_perturbation_gate"
SEEDS = (57061, 57062, 57063)
DONOR_COUNTS = (4, 6, 8, 12)
EFFECT_SCALES = (0.60, 0.80, 1.00)
N_SCREENS = 500
N_CANDIDATES = 24
N_GUIDES = 3
N_OUTCOMES = 5
ALPHA = 0.05
VIABILITY_MARGIN = -0.50
CLASS_NAMES = (
    "broad_rescue",
    "narrow_one_endpoint",
    "tradeoff",
    "toxic_pseudorescue",
    "null",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--outdir", type=Path, default=DEFAULT_OUTDIR)
    return parser.parse_args()


def write_tsv(path: Path, rows: list[dict[str, object]], fields: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as handle:
        writer = csv.DictWriter(
            handle, delimiter="\t", fieldnames=fields, lineterminator="\n"
        )
        writer.writeheader()
        writer.writerows(rows)


def correlated_noise(
    rng: np.random.Generator, shape: tuple[int, ...], sd: float, chol: np.ndarray
) -> np.ndarray:
    z = rng.normal(size=shape + (N_OUTCOMES,))
    with np.errstate(over="raise", invalid="raise"):
        return sd * np.einsum("...i,ji->...j", z, chol, optimize=True)


def truth_matrix(scale: float) -> tuple[np.ndarray, np.ndarray]:
    effects = np.zeros((N_CANDIDATES, N_OUTCOMES), dtype=float)
    labels = np.empty(N_CANDIDATES, dtype=object)

    effects[0:4, :4] = scale * np.array([1.00, 0.90, 0.85, 0.80])
    effects[0:4, 4] = -0.05
    labels[0:4] = "broad_rescue"

    effects[4:8, 0] = 1.10 * scale
    labels[4:8] = "narrow_one_endpoint"

    effects[8:12, :4] = scale * np.array([1.00, 0.80, -0.50, -0.40])
    effects[8:12, 4] = -0.10
    labels[8:12] = "tradeoff"

    effects[12:16, :4] = scale * np.array([1.00, 0.80, 0.70, 0.60])
    effects[12:16, 4] = -1.00
    labels[12:16] = "toxic_pseudorescue"

    labels[16:24] = "null"
    return effects, labels


def one_sided_p(values: np.ndarray, axis: int) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    n = values.shape[axis]
    mean = values.mean(axis=axis)
    sd = values.std(axis=axis, ddof=1)
    se = sd / np.sqrt(n)
    t_stat = np.divide(mean, se, out=np.zeros_like(mean), where=se > 0)
    p = stats.t.sf(t_stat, df=n - 1)
    return mean, se, p


def evaluate_selection(
    selected: np.ndarray, labels: np.ndarray
) -> dict[str, float]:
    broad = labels == "broad_rescue"
    non_broad = ~broad
    selected_broad = selected[:, broad]
    selected_non_broad = selected[:, non_broad]
    n_selected = int(selected.sum())
    n_selected_broad = int(selected_broad.sum())
    return {
        "prob_any_broad_rescue": float(selected_broad.any(axis=1).mean()),
        "prob_any_false_promotion": float(selected_non_broad.any(axis=1).mean()),
        "broad_rescue_recall": float(n_selected_broad / (selected.shape[0] * broad.sum())),
        "selection_precision": float(n_selected_broad / n_selected) if n_selected else 1.0,
        "mean_n_selected": float(selected.sum(axis=1).mean()),
    }


def run_cell(
    seed: int, donors: int, effect_scale: float
) -> tuple[list[dict[str, object]], list[dict[str, object]]]:
    rng = np.random.default_rng(seed * 10_000 + donors * 100 + int(effect_scale * 100))
    effects, labels = truth_matrix(effect_scale)
    corr = np.full((N_OUTCOMES, N_OUTCOMES), 0.10)
    corr[:4, :4] = 0.25
    np.fill_diagonal(corr, 1.0)
    chol = np.linalg.cholesky(corr)
    guide_factors = np.array([0.85, 1.00, 1.15])

    fixed = effects[None, :, None, None, :] * guide_factors[None, None, None, :, None]
    donor_global = correlated_noise(rng, (N_SCREENS, 1, donors, 1), 0.15, chol)
    candidate_donor = correlated_noise(
        rng, (N_SCREENS, N_CANDIDATES, donors, 1), 0.30, chol
    )
    guide_noise = correlated_noise(
        rng, (N_SCREENS, N_CANDIDATES, 1, N_GUIDES), 0.10, chol
    )
    measurement = correlated_noise(
        rng, (N_SCREENS, N_CANDIDATES, donors, N_GUIDES), 0.45, chol
    )
    observed = fixed + donor_global + candidate_donor + guide_noise + measurement

    donor_means = observed.mean(axis=3)
    guide_means = observed.mean(axis=2)

    scalar_by_donor = donor_means[..., :4].mean(axis=-1)
    _, _, scalar_p = one_sided_p(scalar_by_donor, axis=2)
    mean_viability = donor_means[..., 4].mean(axis=2)
    selected_scalar = (scalar_p <= ALPHA / N_CANDIDATES) & (
        mean_viability > VIABILITY_MARGIN
    )

    _, _, efficacy_p = one_sided_p(donor_means[..., :4], axis=2)
    p_sorted = np.sort(efficacy_p, axis=-1)
    partial_conjunction_p = np.minimum(1.0, 2.0 * p_sorted[..., 2])
    efficacy_pass = partial_conjunction_p <= ALPHA / N_CANDIDATES

    viability_mean, viability_se, _ = one_sided_p(donor_means[..., 4], axis=2)
    simultaneous_t = stats.t.ppf(1.0 - ALPHA / N_CANDIDATES, df=donors - 1)
    viability_lower = viability_mean - simultaneous_t * viability_se
    viability_pass = viability_lower > VIABILITY_MARGIN

    total_scalar = scalar_by_donor.sum(axis=2, keepdims=True)
    loo_scalar = (total_scalar - scalar_by_donor) / (donors - 1)
    donor_pass = loo_scalar.min(axis=2) > 0.0
    guide_scalar = guide_means[..., :4].mean(axis=-1)
    guide_pass = (guide_scalar > 0.0).sum(axis=2) >= 2
    selected_gate = efficacy_pass & viability_pass & donor_pass & guide_pass

    performance_rows: list[dict[str, object]] = []
    for method, selected in (
        ("averaged_endpoint", selected_scalar),
        ("replicated_broad_rescue", selected_gate),
    ):
        metrics = evaluate_selection(selected, labels)
        performance_rows.append(
            {
                "seed": seed,
                "donors": donors,
                "effect_scale": f"{effect_scale:.2f}",
                "method": method,
                **{key: f"{value:.6f}" for key, value in metrics.items()},
            }
        )

    class_rows: list[dict[str, object]] = []
    for method, selected in (
        ("averaged_endpoint", selected_scalar),
        ("replicated_broad_rescue", selected_gate),
    ):
        for class_name in CLASS_NAMES:
            mask = labels == class_name
            class_rows.append(
                {
                    "seed": seed,
                    "donors": donors,
                    "effect_scale": f"{effect_scale:.2f}",
                    "method": method,
                    "truth_class": class_name,
                    "candidate_selection_probability": f"{selected[:, mask].mean():.6f}",
                }
            )
    return performance_rows, class_rows


def build_report(
    performance_rows: list[dict[str, object]],
    gate_rows: list[dict[str, object]],
    overall_status: str,
) -> str:
    key_rows = [
        row
        for row in performance_rows
        if int(row["donors"]) >= 8 and float(row["effect_scale"]) >= 0.80
    ]
    methods = ("averaged_endpoint", "replicated_broad_rescue")
    summaries: dict[str, dict[str, float]] = {}
    for method in methods:
        rows = [row for row in key_rows if row["method"] == method]
        summaries[method] = {
            key: float(np.mean([float(row[key]) for row in rows]))
            for key in (
                "prob_any_broad_rescue",
                "prob_any_false_promotion",
                "broad_rescue_recall",
                "selection_precision",
            )
        }
    failed = [row for row in gate_rows if row["status"] == "FAIL"]
    donor_gate = {
        donors: all(
            row["status"] == "PASS"
            for row in gate_rows
            if int(row["donors"]) == donors
        )
        for donors in (8, 12)
    }
    return f"""# V57 Multi-Criterion Perturbation Gate

Status: **{overall_status}** as a synthetic method test. This report contains no
biological observations and makes no MS, target, or treatment claim.

## Scale

- Seeded synthetic screens: `{len(SEEDS) * len(DONOR_COUNTS) * len(EFFECT_SCALES) * N_SCREENS:,}`.
- Candidate evaluations: `{len(SEEDS) * len(DONOR_COUNTS) * len(EFFECT_SCALES) * N_SCREENS * N_CANDIDATES:,}` per method.
- Methods compared: multiplicity-controlled averaged efficacy endpoint versus
  the preregistered partial-conjunction, viability, donor, and guide gate.

## Preregistered Operating Region

Across donor counts `>=8` and broad-rescue effects `>=0.80`, the averaged
endpoint had mean probability of any true rescue
`{summaries['averaged_endpoint']['prob_any_broad_rescue']:.3f}`, false promotion
`{summaries['averaged_endpoint']['prob_any_false_promotion']:.3f}`, recall
`{summaries['averaged_endpoint']['broad_rescue_recall']:.3f}`, and precision
`{summaries['averaged_endpoint']['selection_precision']:.3f}`.

The replicated broad-rescue gate had corresponding values
`{summaries['replicated_broad_rescue']['prob_any_broad_rescue']:.3f}`,
`{summaries['replicated_broad_rescue']['prob_any_false_promotion']:.3f}`,
`{summaries['replicated_broad_rescue']['broad_rescue_recall']:.3f}`, and
`{summaries['replicated_broad_rescue']['selection_precision']:.3f}`.

Preregistered checks failed: `{len(failed)}` of `{len(gate_rows)}`. Full
cell-level checks are in `gate_checks.tsv`; no threshold was changed after
simulation.

The eight-donor design is `{'PASS' if donor_gate[8] else 'FAIL'}` and the
twelve-donor design is `{'PASS' if donor_gate[12] else 'FAIL'}` across all
frozen seeds and tested effects. Thus `12` is the first **tested** donor count
with a fully passing operating region; this sweep does not establish whether
`9`, `10`, or `11` donors suffice.

## Interpretation

The averaged endpoint was sensitive but frequently promoted narrow or tradeoff
effects. The replicated gate eliminated false promotions in this synthetic
design but was underpowered at eight donors. The gate is useful only within an
operating region that passed every frozen criterion. A failure must not be
rescued by changing endpoints, margins, or multiplicity rules afterward. Even
a method pass only defines how a future human-cell experiment would select a
broadly beneficial, non-toxic, donor-replicated perturbation; it does not
establish that such a perturbation exists.

## Files

- `performance.tsv`: screen-level operating characteristics aggregated by
  seed, donor count, effect scale, and method.
- `class_selection.tsv`: selection frequency by synthetic truth class.
- `gate_checks.tsv`: frozen pass/fail criteria.
- `synthetic/simulation_config.json`: exact seeded design declaration.
"""


def main() -> int:
    args = parse_args()
    outdir = args.outdir
    (outdir / "synthetic").mkdir(parents=True, exist_ok=True)
    performance_rows: list[dict[str, object]] = []
    class_rows: list[dict[str, object]] = []
    for seed in SEEDS:
        for donors in DONOR_COUNTS:
            for effect_scale in EFFECT_SCALES:
                perf, classes = run_cell(seed, donors, effect_scale)
                performance_rows.extend(perf)
                class_rows.extend(classes)

    perf_fields = [
        "seed",
        "donors",
        "effect_scale",
        "method",
        "prob_any_broad_rescue",
        "prob_any_false_promotion",
        "broad_rescue_recall",
        "selection_precision",
        "mean_n_selected",
    ]
    class_fields = [
        "seed",
        "donors",
        "effect_scale",
        "method",
        "truth_class",
        "candidate_selection_probability",
    ]
    write_tsv(outdir / "performance.tsv", performance_rows, perf_fields)
    write_tsv(outdir / "class_selection.tsv", class_rows, class_fields)

    lookup = {
        (int(row["seed"]), int(row["donors"]), float(row["effect_scale"]), str(row["method"])): row
        for row in performance_rows
    }
    gate_rows: list[dict[str, object]] = []
    for seed in SEEDS:
        for donors in (8, 12):
            for effect_scale in (0.80, 1.00):
                gate = lookup[(seed, donors, effect_scale, "replicated_broad_rescue")]
                scalar = lookup[(seed, donors, effect_scale, "averaged_endpoint")]
                checks = {
                    "false_promotion_le_0.05": float(gate["prob_any_false_promotion"]) <= 0.05,
                    "any_true_rescue_ge_0.80": float(gate["prob_any_broad_rescue"]) >= 0.80,
                    "precision_ge_0.90": float(gate["selection_precision"]) >= 0.90,
                    "false_promotion_below_average": float(gate["prob_any_false_promotion"])
                    < float(scalar["prob_any_false_promotion"]),
                    "true_rescue_loss_le_0.10": float(gate["prob_any_broad_rescue"])
                    >= float(scalar["prob_any_broad_rescue"]) - 0.10,
                }
                for check, passed in checks.items():
                    gate_rows.append(
                        {
                            "seed": seed,
                            "donors": donors,
                            "effect_scale": f"{effect_scale:.2f}",
                            "check": check,
                            "status": "PASS" if passed else "FAIL",
                        }
                    )
    write_tsv(
        outdir / "gate_checks.tsv",
        gate_rows,
        ["seed", "donors", "effect_scale", "check", "status"],
    )
    overall_status = "PASS" if all(row["status"] == "PASS" for row in gate_rows) else "FAIL"
    config = {
        "synthetic": True,
        "purpose": "method behavior only; no biological or MS claim",
        "seeds": list(SEEDS),
        "donor_counts": list(DONOR_COUNTS),
        "effect_scales": list(EFFECT_SCALES),
        "screens_per_cell": N_SCREENS,
        "n_candidates": N_CANDIDATES,
        "n_guides": N_GUIDES,
        "n_efficacy_outcomes": 4,
        "viability_margin": VIABILITY_MARGIN,
        "family_alpha": ALPHA,
        "candidate_truth_class_counts": {
            "broad_rescue": 4,
            "narrow_one_endpoint": 4,
            "tradeoff": 4,
            "toxic_pseudorescue": 4,
            "null": 8,
        },
    }
    (outdir / "synthetic/simulation_config.json").write_text(
        json.dumps(config, indent=2, sort_keys=True) + "\n"
    )
    summary = {
        "synthetic": True,
        "purpose": "V57 multi-criterion perturbation-gate characterization; no biological claim",
        "n_synthetic_screens": len(SEEDS)
        * len(DONOR_COUNTS)
        * len(EFFECT_SCALES)
        * N_SCREENS,
        "n_candidate_evaluations_per_method": len(SEEDS)
        * len(DONOR_COUNTS)
        * len(EFFECT_SCALES)
        * N_SCREENS
        * N_CANDIDATES,
        "n_gate_checks": len(gate_rows),
        "n_gate_fail": sum(row["status"] == "FAIL" for row in gate_rows),
        "overall_status": overall_status,
    }
    (outdir / "summary.json").write_text(
        json.dumps(summary, indent=2, sort_keys=True) + "\n"
    )
    (outdir / "REPORT.md").write_text(
        build_report(performance_rows, gate_rows, overall_status)
    )
    print(json.dumps(summary, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
